* NEWS
Sun Nov 28 10:59:29 PST 2010:
- Updated the bundle for the latest Message and Mail framework UUIDs.
- Version is 1.1.4

* About
The reply in Mail.app creates a new email with the preamble

On 21 July 2010, John Doe wrote:

....


When forward, the first few lines is the 

From:
Subject:
Date:

etc.

ReplyWithHeaders causes the reply message to behave like forwarding. I developed
this a long time back on someones request. I don't use it much myself nor do I
spend time developing it.  So if things break, I might not fix things quickly.

* Requirements:
At least

Mail: Version 4.3 (1081)

Snow Leopard: 10.6.4

* Installation

1. Quit Mail.app
2. Save and unzip the attachment in ~/Library/Mail/Bundles (create the directory if missing)
   Unzipping will return "ReplyWithHeaders.mailbundle" - copy this to ~/Library/Mail/Bundles
3. In the terminal:

   > defaults write com.apple.mail EnableBundles -bool true

   > defaults write com.apple.mail BundleCompatibilityVersion 4
4. Start Console.app (/Applications/Utilities)
5. In the search bar (top right corner of Console.app) type: Mail

   This will restrict your information to Mail.app messages
6. Restart Mail.app

In the console, if all goes well, you should see

ReplyWithHeaders: Oh its a wonderful life

Loaded ReplyWithHeaders

