/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface NSAttributedString (MailAttributedStringToHTML)
- (id)webArchiveForRange:(struct _NSRange)arg1 signatureID:(id *)arg2 fixUpNewlines:(BOOL)arg3;
- (id)webArchiveForRange:(struct _NSRange)arg1 signatureID:(id *)arg2;
- (id)webArchiveForRange:(struct _NSRange)arg1 fixUpNewlines:(BOOL)arg2;
- (id)webArchiveForRange:(struct _NSRange)arg1;
@end